name: Publish to MCP Registry

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 'lts/*'

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run type check
        run: npm run type-check

      - name: Install MCP Publisher
        run: |
          URL="https://github.com/modelcontextprotocol/registry/releases/latest/download/mcp-publisher_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/;s/aarch64/arm64/').tar.gz"
          echo "Downloading MCP Publisher from: $URL"

          # Download with failure handling
          if ! curl -fL "$URL" -o mcp-publisher.tar.gz; then
            echo "Failed to download MCP Publisher"
            exit 1
          fi

          # Verify the downloaded file is a valid gzip archive
          if ! file mcp-publisher.tar.gz | grep -q 'gzip compressed'; then
            echo "Downloaded file is not a valid gzip archive"
            echo "File type: $(file mcp-publisher.tar.gz)"
            echo "File contents:"
            cat mcp-publisher.tar.gz
            exit 1
          fi

          # Extract the archive
          tar xzf mcp-publisher.tar.gz

          # Verify the binary was extracted successfully
          if [ ! -f mcp-publisher ]; then
            echo "mcp-publisher binary not found after extraction"
            exit 1
          fi

          # Make it executable
          chmod +x mcp-publisher

          echo "MCP Publisher installed successfully"

      - name: Login to MCP Registry
        run: ./mcp-publisher login github-oidc

      - name: Publish to MCP Registry
        run: ./mcp-publisher publish
